species: arabidopsis

seq_info:
  type: RNA-Seq
  stranded: yes
  mode: PE
  replicate: 3
  #replicate: 3+4+3+3 (if the number of replicates are different for each sample)

path: /cluster/home/lpeng/projects/ZHM/Hedanxia/HMZ0073_20200213/RNA-Seq/fastq

samples:
        - mock1
        - mock2
        - mock3
        - fmock1
        - fmock2
        - fmock3
        - Naringenine_0.1uM1
        - Naringenine_0.1uM2
        - Naringenine_0.1uM3
        - Naringenine_1uM1
        - Naringenine_1uM2
        - Naringenine_1uM3
        - Naring3_100uM
        - Naring4_100uM
        - Naring5_100uM
 

groups:
        - mock
        - mock
        - mock
        - fmock
        - fmock
        - fmock
        - Naringenine_0.1uM
        - Naringenine_0.1uM
        - Naringenine_0.1uM
        - Naringenine_1uM
        - Naringenine_1uM
        - Naringenine_1uM
        - Naring_100uM
        - Naring_100uM
        - Naring_100uM


design_table: design_table.tsv
#design_table: none

venn_table: venn_table.tsv

cpu: 30

strandness_hisat2: RF ## R (SE); RF (PE)

strandness_htseq: reverse

Rscript_path: /cluster/home/xfu/R/3.5.1/bin/Rscript

conda_path: /cluster/home/xfu/miniconda2/envs/gmatic/bin

trinity_path: /cluster/home/lpeng/miniconda3/envs/trinity

uniprot: /cluster/home/lpeng/backup/Metabase/Uniprot/uniprot_sprot

Uniprot_name: /cluster/home/lpeng/backup/Metabase/Uniprot/uniprot_sprot_name.tsv

adapter: /cluster/home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

fold_change: 
  - 1.5
  - 2
  - 2.5
  - 3

# Arabidopsis
#index: /cluster/home/xfu/Gmatic7/genome/tair10/hisat2/tair10
 
#gtf: /cluster/home/xfu/Gmatic7/gene/tair10/tair10.gtf
 
#bed: /cluster/home/xfu/Gmatic7/gene/tair10/tair10_gene.bed
 
#gene_anno: /cluster/home/xfu/Gmatic7/gene/tair10/tair10_gene_anno.tsv
 
#gene_length: ./script/tair10_merged_exons_length.tsv
 
#IGV: /cluster/home/xfu/igv/genomes/tair10.genome

# Nicotiana benthamiana
#index: /cluster/home/xfu/Gmatic7/genome/Niben/hisat2/Niben101
# 
#gtf: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101.gtf
# 
#bed: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_gene.bed
# 
#gene_anno: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_gene_anno_ath.tsv
# 
#gene_length: /cluster/home/xfu/Gmatic7/gene/Niben/Niben101_merged_exons_length.tsv
# 
#IGV: /cluster/home/xfu/igv/genomes/Niben101.genome

